[package]
name = "menoh-sys"
version = "0.1.0"
authors = ["Toru Ogawa <ogawa@preferred.jp>"]
repository = "https://github.com/Hakuyume/menoh-rs"
license-file = "../LICENSE"
readme = "../README.md"
description = "A low-level binding for Menoh."
build = "build.rs"

[dependencies]

[build-dependencies]
pkg-config = "0.3"
