language: rust
env:
  global:
    - MKL_DNN_VERSION=0.14
    - MENOH_VERSION=1.0.2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:maarten-fonville/protobuf'
    packages:
      - gcc-7
      - g++-7
      - libprotobuf-dev
      - protobuf-compiler
cache:
  cargo: true
  directories:
    - $HOME/local
install:
  # mkl-dnn
  - |
    cd
    if [[ ! -f $HOME/local/lib/libmkldnn.so ]]; then
        git clone https://github.com/intel/mkl-dnn.git --branch v$MKL_DNN_VERSION --depth=1
        cd mkl-dnn
        cd scripts && ./prepare_mkl.sh && cd ..
        mkdir -p build
        cd build
        cmake .. \
              -DCMAKE_INSTALL_PREFIX=$HOME/local \
              -DWITH_EXAMPLE=OFF \
              -DWITH_TEST=OFF
        make && make install
    fi
  # menoh
  - |
    cd
    if [[ ! -f $HOME/local/lib/libmenoh.so ]]; then
        git clone https://github.com/pfnet-research/menoh.git --branch v$MENOH_VERSION --depth=1
        cd menoh
        mkdir -p build
        cd build
        CC=gcc-7 CXX=g++-7 cmake .. \
              -DCMAKE_INSTALL_PREFIX=$HOME/local \
              -DENABLE_TEST=OFF \
              -DENABLE_BENCHMARK=OFF \
              -DENABLE_EXAMPLE=OFF \
              -DENABLE_TOOL=OFF
        make && make install
    fi
before_script:
  - |
    cd $TRAVIS_BUILD_DIR
    export LD_LIBRARY_PATH=$HOME/local/lib
    export PKG_CONFIG_PATH=$HOME/local/share/pkgconfig
  - |
    pip3 install chainer onnx-chainer
    python3 make_onnx.py menoh/MLP.onnx
    curl -L https://github.com/Hakuyume/menoh-rs/releases/download/assets/test.onnx -o menoh/test.onnx
    echo 16431ac1fb35576d14ba53e7d0000ef4644b24a5217827f9297c6bae11437a93 menoh/test.onnx | sha256sum -c
