platform:
  - x64
environment:
  matrix:
    - channel: stable
      target: msvc
    - channel: nightly
      target: msvc
    - channel: stable
      target: gnu
    - channel: nightly
      target: gnu
install:
  - set SSL_CERT_FILE=C:\msys64\mingw64\ssl\cert.pem
  - set SSL_CERT_DIR=C:\msys64\mingw64\ssl\certs
  - if [%target%]==[msvc] set PATH=C:\msys64\mingw64\bin;%PATH%
  - if [%target%]==[gnu] set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

  - curl -LO https://win.rustup.rs/rustup-init.exe
  - rustup-init -y --verbose --default-toolchain %channel% --default-host x86_64-pc-windows-%target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version
  - cargo --version

  - if [%target%]==[msvc] curl -LO https://github.com/pfnet-research/menoh/releases/download/v1.0.2/menoh_prebuild_win_v1.0.2.zip
  - if [%target%]==[msvc] 7z x menoh_prebuild_win_v1.0.2.zip
  - if [%target%]==[msvc] set PATH=c:\projects\menoh-rs\menoh_prebuild_win_v1.0.2\bin;%PATH%
  - if [%target%]==[msvc] set LIB=c:\projects\menoh-rs\menoh_prebuild_win_v1.0.2\lib
build: false
test_script:
  - cargo test --verbose
