platform:
  - x64
environment:
  matrix:
    - channel: stable
      target: msvc
    - channel: nightly
      target: msvc
    - channel: stable
      target: gnu
    - channel: nightly
      target: gnu
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --verbose --default-toolchain %channel% --default-host x86_64-pc-windows-%target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version
  - cargo --version

  - if [%target%]==[msvc] appveyor DownloadFile https://github.com/pfnet-research/menoh/releases/download/v1.0.2/ -FileName menoh_prebuild_win_v1.0.2.zip
  - if [%target%]==[msvc] 7z x menoh_prebuild_win_v1.0.2.zip
  - if [%target%]==[msvc] set PATH=c:\projects\menoh-rs\menoh_prebuild_win_v1.0.2\bin;%PATH%
  - if [%target%]==[msvc] set LIB=c:\projects\menoh-rs\menoh_prebuild_win_v1.0.2\lib
build: false
test_script:
  - cargo test --verbose
